Repository huro3h/study_records, pull requests merged in 2023-01, with the labels that each got.

#23 Feature/cg 44/edit subject master in japanese
  app/views/shared/_header.html.erb
  app/views/subjects/_form.html.erb
  app/views/subjects/_subject.html.erb
  app/views/subjects/index.html.erb
  app/views/subjects/new.html.erb
  spec/system/tops_spec.rb
Labels: need review

#21 セッション機能を追加
  app/controllers/application_controller.rb
  app/controllers/sessions_controller.rb
  app/controllers/study_records_controller.rb
  app/controllers/subjects_controller.rb
  app/controllers/tops_controller.rb
  app/controllers/users_controller.rb
  app/helpers/sessions_helper.rb
  app/views/shared/_header.html.erb
  app/views/static_pages/home.html.erb
  app/views/tops/index.html.erb
  config/routes.rb
  spec/factories/user.rb
  spec/rails_helper.rb
  spec/requests/study_recored_spec.rb
  spec/requests/tops_controller_spec.rb
  spec/support/request_spec_helpers.rb
  spec/support/system_spec_helpers.rb
  spec/system/static_pages_spec.rb
  spec/system/tops_spec.rb
Labels: need review

#22 CG-42 ユーザの学習記録をユーザトップページに表示する
  app/controllers/tops_controller.rb
  app/models/study_record.rb
  app/views/shared/_header.html.erb
  app/views/tops/index.html.erb
  spec/factories/study_record.rb
  spec/factories/study_records.rb
  spec/factories/subject.rb
  spec/system/tops_spec.rb
Labels: need review

#24 CG-57 フッターの修正
  app/assets/stylesheets/application.bootstrap.scss
  app/views/shared/_footer.html.erb
  app/views/tops/index.html.erb
Labels: bug, need review

#26 CG-39 グラフ表示機能
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.bootstrap.scss
  app/controllers/tops_controller.rb
  app/javascript/application.js
  app/models/study_record.rb
  app/views/tops/index.html.erb
  package.json
  yarn.lock
Labels: need review, reviewing

#28 CG-49 (教科マスタのテストの追加)
  app/controllers/subjects_controller.rb
  app/views/subjects/show.html.erb
  spec/models/subjects_spec.rb
  spec/requests/subjects_controller_spec.rb
  spec/support/system_spec_helpers.rb
  spec/system/subjects_spec.rb
Labels: need review
